"use client";

import Link from "next/link";
import {
  Activity, ArrowDownLeft, ArrowDownRight, ArrowRight, ArrowUpRight, BarChart3,
  Bell, CalendarDays, Check, ChevronDown, CircleHelp, CreditCard, Download,
  Dumbbell, FileText, Filter, HelpCircle, Home, IndianRupee, LayoutDashboard,
  Menu, MessageCircle, Moon, MoreHorizontal, Plus, ReceiptText, RefreshCw,
  Search, Settings, ShieldCheck, Sparkles, Sun, TrendingUp, Users,
  WalletCards, X, Zap,
} from "lucide-react";
import { useMemo, useState, type ElementType } from "react";

type PaymentStatus = "Paid" | "Pending" | "Failed" | "Refunded";
type PaymentTab = "All" | PaymentStatus;
type Period = "This month" | "Last month" | "Last 3 months";

const payments = [
  { id: "GW-8492", name: "Ananya Verma", initials: "AV", plan: "Annual Unlimited", amount: 18000, date: "08 Aug, 7:42 PM", method: "UPI", status: "Paid" as PaymentStatus, color: "violet" },
  { id: "GW-8491", name: "Rahul Jain", initials: "RJ", plan: "Strength Pro", amount: 2499, date: "08 Aug, 6:18 PM", method: "Visa •• 4812", status: "Paid" as PaymentStatus, color: "blue" },
  { id: "GW-8490", name: "Rohan Kapoor", initials: "RK", plan: "Monthly Flex", amount: 1999, date: "08 Aug, 4:06 PM", method: "Visa •• 0931", status: "Failed" as PaymentStatus, color: "amber" },
  { id: "GW-8489", name: "Ishita Rao", initials: "IR", plan: "Strength Pro", amount: 2499, date: "08 Aug, 1:34 PM", method: "Cash", status: "Pending" as PaymentStatus, color: "pink" },
  { id: "GW-8488", name: "Kabir Singh", initials: "KS", plan: "Annual Unlimited", amount: 18000, date: "07 Aug, 8:22 PM", method: "Net banking", status: "Paid" as PaymentStatus, color: "green" },
  { id: "GW-8487", name: "Neha Sharma", initials: "NS", plan: "Monthly Flex", amount: 1999, date: "07 Aug, 5:15 PM", method: "UPI", status: "Refunded" as PaymentStatus, color: "pink" },
  { id: "GW-8486", name: "Arjun Nair", initials: "AN", plan: "Strength Pro", amount: 2499, date: "07 Aug, 11:08 AM", method: "Mastercard •• 7024", status: "Paid" as PaymentStatus, color: "blue" },
];

const revenue = {
  "This month": { total: "₹12.84L", change: "8.2%", points: [20, 28, 25, 43, 39, 52, 48, 67, 61, 74, 72, 88], previous: [18, 22, 29, 31, 37, 41, 44, 48, 53, 57, 62, 66] },
  "Last month": { total: "₹11.87L", change: "5.4%", points: [16, 22, 31, 27, 39, 45, 43, 56, 54, 67, 69, 78], previous: [14, 20, 23, 28, 32, 37, 43, 46, 51, 55, 59, 64] },
  "Last 3 months": { total: "₹37.62L", change: "12.7%", points: [17, 27, 23, 36, 42, 39, 57, 55, 69, 67, 80, 91], previous: [13, 19, 25, 29, 34, 40, 46, 49, 55, 60, 63, 70] },
} satisfies Record<Period, { total: string; change: string; points: number[]; previous: number[] }>;

const navGroups = [
  { label: "Workspace", items: [{ label: "Overview", icon: LayoutDashboard }, { label: "Members", icon: Users }, { label: "Attendance", icon: Activity }, { label: "Payments", icon: WalletCards, active: true }, { label: "Messages", icon: MessageCircle, badge: "8" }] },
  { label: "Manage", items: [{ label: "Memberships", icon: CreditCard }, { label: "Trainers", icon: Dumbbell }, { label: "Reports", icon: BarChart3 }, { label: "Automations", icon: Zap, badge: "NEW" }] },
];

const money = (amount: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(amount);

function Brand() { return <div className="brand"><div className="brand-mark"><TrendingUp size={18} strokeWidth={2.8} /></div><span>Gymwise</span></div>; }

function Sidebar({ open, close, notify }: { open: boolean; close: () => void; notify: (message: string) => void }) {
  return <>{open && <button className="sidebar-scrim" aria-label="Close navigation" onClick={close} />}<aside className={`sidebar ${open ? "sidebar-open" : ""}`}><div className="sidebar-top"><Brand /><button className="icon-button sidebar-close" onClick={close} aria-label="Close navigation"><X size={18} /></button></div><button className="location-switcher" onClick={() => notify("Location switcher opened")}><span className="location-icon"><Dumbbell size={17} /></span><span><strong>Pulse Fitness</strong><small>South Delhi</small></span><ChevronDown size={15} /></button><nav className="main-nav" aria-label="Primary navigation">{navGroups.map(group => <div className="nav-group" key={group.label}><div className="nav-label">{group.label}</div>{group.items.map(({ label, icon: Icon, active, badge }) => { const route = ({ Overview: "/", Members: "/members", Attendance: "/attendance", Payments: "/payments", Messages: "/messages", Memberships: "/memberships", Trainers: "/trainers", Reports: "/reports", Automations: "/automations" } as Record<string, string>)[label]; return <Link className={`nav-item ${active ? "active" : ""}`} href={route} key={label} onClick={close}><Icon size={18} strokeWidth={active ? 2.2 : 1.8} /><span>{label}</span>{badge && <span className={`nav-badge ${badge === "NEW" ? "new" : ""}`}>{badge}</span>}</Link>; })}</div>)}</nav><div className="sidebar-bottom"><div className="insight-card"><span className="insight-icon"><Sparkles size={16} /></span><strong>Payment insight</strong><p>UPI collections are up 24% this month.</p><button onClick={() => notify("Payment insight opened")}>View insight <ArrowUpRight size={14} /></button></div><button className="nav-item" onClick={() => notify("Settings opened")}><Settings size={18} /><span>Settings</span></button><button className="nav-item" onClick={() => notify("Help centre opened")}><CircleHelp size={18} /><span>Help & support</span></button></div></aside></>;
}

function ThemeToggle() {
  function toggle() { const dark = document.documentElement.dataset.theme !== "dark"; document.documentElement.dataset.theme = dark ? "dark" : "light"; localStorage.setItem("gymwise-theme", dark ? "dark" : "light"); }
  return <button className="icon-button theme-button" onClick={toggle} aria-label="Toggle color theme"><Sun className="theme-sun" size={18} /><Moon className="theme-moon" size={18} /></button>;
}

function Header({ onMenu, notify }: { onMenu: () => void; notify: (message: string) => void }) {
  return <header className="topbar"><div className="topbar-left"><button className="icon-button menu-button" onClick={onMenu} aria-label="Open navigation"><Menu size={20} /></button><div className="mobile-brand"><Brand /></div><button className="search-box" onClick={() => document.getElementById("payment-search")?.focus()}><Search size={16} /><span>Search members, payments...</span><kbd>⌘ K</kbd></button></div><div className="topbar-actions"><button className="icon-button help-button" onClick={() => notify("Help centre opened")} aria-label="Help"><HelpCircle size={18} /></button><ThemeToggle /><button className="icon-button notification-button" onClick={() => notify("You have 3 new notifications")} aria-label="Notifications"><Bell size={18} /><i /></button><div className="topbar-divider" /><button className="profile" onClick={() => notify("Profile menu opened")}><span className="avatar avatar-main">PK</span><span className="profile-copy"><strong>Priya Khanna</strong><small>Owner</small></span><ChevronDown size={15} /></button></div></header>;
}

function Stat({ icon: Icon, tone, label, value, detail, change }: { icon: ElementType; tone: string; label: string; value: string; detail: string; change?: string }) {
  return <article className="kpi-card payment-kpi"><div className="kpi-top"><div className={`kpi-icon ${tone}`}><Icon size={18} /></div><div className="kpi-copy"><div className="kpi-label">{label}<button aria-label={`About ${label}`}><CircleHelp size={13} /></button></div><div className="kpi-value-row"><strong>{value}</strong>{change && <span className={change.startsWith("-") ? "negative" : "positive"}>{change.startsWith("-") ? <ArrowDownRight size={12} /> : <ArrowUpRight size={12} />}{change.replace(/[+-]/, "")}</span>}</div></div></div><p>{detail}</p></article>;
}

function RevenueChart({ period }: { period: Period }) {
  const data = revenue[period], width = 760, height = 190;
  const path = (values: number[]) => values.map((value, index) => `${index ? "L" : "M"}${index / (values.length - 1) * width},${height - value / 100 * height}`).join(" ");
  const current = path(data.points), lastY = height - data.points[data.points.length - 1] / 100 * height;
  return <div className="revenue-chart" aria-label={`Revenue chart for ${period}`}><div className="chart-axis"><span>₹1.5L</span><span>₹1.0L</span><span>₹50K</span><span>₹0</span></div><svg viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none" role="img"><defs><linearGradient id="revenueArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#6f57e8" stopOpacity=".24" /><stop offset="100%" stopColor="#6f57e8" stopOpacity="0" /></linearGradient></defs>{[0, 63, 126, 189].map(y => <line key={y} x1="0" x2={width} y1={y} y2={y} className="payment-grid-line" />)}<path d={`${current} L${width},${height} L0,${height} Z`} fill="url(#revenueArea)" /><path d={path(data.previous)} className="previous-revenue-line" /><path d={current} className="revenue-line" /><circle cx={width} cy={lastY} r="7" className="revenue-dot-ring" /><circle cx={width} cy={lastY} r="3.5" className="revenue-dot" /></svg><div className="chart-months"><span>1 Aug</span><span>8 Aug</span><span>15 Aug</span><span>22 Aug</span><span>31 Aug</span></div><div className="chart-key"><span><i />This period</span><span><i />Previous period</span></div></div>;
}

function RecordModal({ close, notify }: { close: () => void; notify: (message: string) => void }) {
  return <div className="modal-layer" role="dialog" aria-modal="true" aria-labelledby="record-title" onMouseDown={event => event.currentTarget === event.target && close()}><form className="modal payment-modal" onSubmit={event => { event.preventDefault(); close(); notify("Payment recorded successfully"); }}><div className="modal-header"><div><h2 id="record-title">Record a payment</h2><p>Add an offline or manual member payment.</p></div><button type="button" className="icon-button" onClick={close} aria-label="Close"><X size={18} /></button></div><label>Member<input required autoFocus placeholder="Search by member name or phone" /></label><div className="form-row"><label>Amount<input required type="number" min="1" placeholder="₹ 0" /></label><label>Payment method<select defaultValue="" required><option value="" disabled>Select method</option><option>UPI</option><option>Cash</option><option>Card</option><option>Bank transfer</option></select></label></div><label>Payment note <span>Optional</span><input placeholder="e.g. August membership fee" /></label><div className="secure-note"><ShieldCheck size={15} /> This payment will be added to the member ledger.</div><div className="modal-actions"><button type="button" className="button secondary" onClick={close}>Cancel</button><button className="button primary" type="submit"><Check size={16} /> Record payment</button></div></form></div>;
}

export default function PaymentsPage() {
  const [period, setPeriod] = useState<Period>("This month"), [tab, setTab] = useState<PaymentTab>("All"), [query, setQuery] = useState(""), [mobileNav, setMobileNav] = useState(false), [modal, setModal] = useState(false), [toast, setToast] = useState("");
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2600); };
  const visible = useMemo(() => payments.filter(payment => (tab === "All" || payment.status === tab) && `${payment.name} ${payment.id} ${payment.plan} ${payment.method}`.toLowerCase().includes(query.trim().toLowerCase())), [tab, query]);
  const counts: Record<PaymentTab, number> = { All: payments.length, Paid: 4, Pending: 1, Failed: 1, Refunded: 1 };
  function exportPayments() { const rows = payments.map(payment => [payment.id, payment.name, payment.plan, payment.date, payment.method, payment.amount, payment.status].join(",")); const url = URL.createObjectURL(new Blob([["Payment ID,Member,Plan,Date,Method,Amount,Status", ...rows].join("\n")], { type: "text/csv" })); const link = document.createElement("a"); link.href = url; link.download = "gymwise-payments.csv"; link.click(); URL.revokeObjectURL(url); notify("Payments exported successfully"); }

  return <div className="app-shell"><Sidebar open={mobileNav} close={() => setMobileNav(false)} notify={notify} /><div className="app-content"><Header onMenu={() => setMobileNav(true)} notify={notify} /><main className="dashboard payments-dashboard">
    <div className="page-heading payments-heading"><div><h1>Payments</h1><p>Track collections, settlements, and member transactions.</p></div><div className="heading-actions"><div className="period-select"><CalendarDays size={16} /><select value={period} onChange={event => setPeriod(event.target.value as Period)} aria-label="Payment period"><option>This month</option><option>Last month</option><option>Last 3 months</option></select><ChevronDown size={14} /></div><button className="button secondary export-button" onClick={exportPayments}><Download size={16} /> Export</button><button className="button primary" onClick={() => setModal(true)}><Plus size={17} /> Record payment</button></div></div>
    <section className="kpi-grid" aria-label="Payment summary"><Stat icon={IndianRupee} tone="purple" label="Total collected" value={revenue[period].total} change={`+${revenue[period].change}`} detail="Across 1,426 successful payments" /><Stat icon={ReceiptText} tone="blue" label="Pending amount" value="₹1.76L" detail="43 payments awaiting collection" /><Stat icon={RefreshCw} tone="amber" label="Failed payments" value="₹84,800" change="-3.1%" detail="12 payments need attention" /><Stat icon={TrendingUp} tone="green" label="Collection rate" value="91.4%" change="+2.6%" detail="Target for August: 94%" /></section>
    <section className="payments-overview-grid"><article className="panel revenue-panel"><div className="payment-card-header"><div><h2>Collection overview</h2><p>Revenue received across all payment methods</p></div><div className="revenue-summary"><div><small>Total collected</small><strong>{revenue[period].total}</strong></div><span><ArrowUpRight size={13} /> {revenue[period].change}</span></div></div><RevenueChart period={period} /></article><div className="payments-side"><article className="settlement-card"><div className="settlement-top"><span><ArrowDownLeft size={18} /></span><div><small>Next settlement</small><strong>₹2,46,820</strong></div><em>On track</em></div><div className="settlement-meta"><div><span>Expected by</span><strong>Mon, 10 Aug</strong></div><div><span>Bank account</span><strong>HDFC •• 2481</strong></div></div><button onClick={() => notify("Settlement details opened")}>View settlement details <ArrowRight size={14} /></button></article><article className="panel methods-panel"><div className="payment-card-header compact"><div><h2>Payment methods</h2><p>Share of collections this month</p></div><button className="icon-button small" onClick={() => notify("Payment method report opened")}><MoreHorizontal size={18} /></button></div><div className="method-content"><div className="donut"><div><strong>1,426</strong><span>payments</span></div></div><div className="method-list">{[["UPI", "48%", "₹6.16L", "purple"], ["Cards", "31%", "₹3.98L", "blue"], ["Cash", "14%", "₹1.80L", "green"], ["Net banking", "7%", "₹89.9K", "amber"]].map(([name, share, amount, color]) => <div className="method-row" key={name}><i className={color} /><span>{name}</span><strong>{share}</strong><small>{amount}</small></div>)}</div></div></article></div></section>
    <article className="panel transactions-panel"><div className="transactions-header"><div><h2>Recent transactions</h2><p>Track and manage every member payment</p></div><button className="text-button" onClick={() => notify("All transactions loaded")}>View all <ArrowRight size={14} /></button></div><div className="transaction-toolbar"><div className="payment-tabs">{(["All", "Paid", "Pending", "Failed", "Refunded"] as PaymentTab[]).map(item => <button key={item} onClick={() => setTab(item)} className={tab === item ? "selected" : ""}>{item}<span>{counts[item]}</span></button>)}</div><div className="transaction-tools"><label className="transaction-search"><Search size={15} /><input id="payment-search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search payments" />{query && <button onClick={() => setQuery("")} aria-label="Clear search"><X size={13} /></button>}</label><button className="icon-button table-filter" onClick={() => notify("Advanced filters opened")}><Filter size={16} /></button></div></div><div className="payments-table-wrap"><table className="payments-table"><thead><tr><th>Member</th><th>Payment ID</th><th>Date & time</th><th>Method</th><th>Amount</th><th>Status</th><th /></tr></thead><tbody>{visible.map(payment => <tr key={payment.id} onClick={() => notify(`${payment.id} details opened`)}><td><div className="member-cell"><span className={`avatar ${payment.color}`}>{payment.initials}</span><div><strong>{payment.name}</strong><small>{payment.plan}</small></div></div></td><td><span className="payment-id">{payment.id}</span></td><td><span className="payment-date">{payment.date}</span></td><td><span className="payment-method">{payment.method === "UPI" ? <Zap size={13} /> : payment.method.includes("Visa") || payment.method.includes("Mastercard") ? <CreditCard size={13} /> : payment.method === "Cash" ? <IndianRupee size={13} /> : <FileText size={13} />}{payment.method}</span></td><td><strong className="amount-cell">{money(payment.amount)}</strong></td><td><span className={`status-pill ${payment.status.toLowerCase()}`}><i />{payment.status}</span></td><td><button className="icon-button small" onClick={event => { event.stopPropagation(); notify(`Actions opened for ${payment.id}`); }}><MoreHorizontal size={17} /></button></td></tr>)}{visible.length === 0 && <tr><td colSpan={7}><div className="payment-empty"><ReceiptText size={25} /><strong>No payments found</strong><span>Try a different search or status.</span><button onClick={() => { setQuery(""); setTab("All"); }}>Clear filters</button></div></td></tr>}</tbody></table></div><div className="table-footer"><span>Showing {visible.length} of 1,426 transactions</span><div><button disabled>Previous</button><button className="current">1</button><button>2</button><button>3</button><span>…</span><button>48</button><button>Next</button></div></div></article>
    <footer className="dashboard-footer"><span>Last updated a few seconds ago</span><span><ShieldCheck size={14} /> Payments are encrypted and securely processed</span></footer>
  </main></div><nav className="mobile-tabs" aria-label="Mobile navigation"><Link href="/"><Home size={19} /><span>Home</span></Link><Link href="/members"><Users size={19} /><span>Members</span></Link><button className="mobile-add" onClick={() => setModal(true)}><Plus size={21} /></button><Link className="active" href="/payments"><WalletCards size={19} /><span>Payments</span></Link><button><Settings size={19} /><span>Settings</span></button></nav>{modal && <RecordModal close={() => setModal(false)} notify={notify} />}{toast && <div className="toast" role="status"><span><Check size={15} /></span>{toast}</div>}</div>;
}
